### PR TITLE
Revert "🚀 Astro v3.3"

### PR DESCRIPTION
**Pull request by srbhr**
Reverts srbhr/website-for-resume-matcher#15

### CODE REVIEW

**Comment by srbhr** [comment]
@xmok there's a problem with the latest deployment. 

Vercel build keep waiting for astro-compress. 

image
image
Need to update those dependencies as well.

**Comment by xmok** [comment]
Hey srbhr!

Seems odd that the previews are building fine but production build fails 🤔 .

We could remove the ```astro-compress``` integration as Astro 3.3. compresses HTML by default. For the other errors like @astro/image, there shouldn't be any references since we're not using that anymore. Is there a reason you're not checking in a *-lock.json file? That might help as well.

Let me know how you'd like to proceed and we'll come up with a new PR.

**Comment by srbhr** [comment]
Yes, we need to find a way to fix this. Let's remove the Astro Compress because as per logs @xmok that's the only thing causing errors.

**Comment by xmok** [comment]
Check out PR #19.

**Pull request closed without merging**
